[package]
name = "rust-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rodio = "0.15"
clap = "3.2.5"
anyhow = "1.0.58"
macroquad = "0.3"